# Generated by Django 4.1.7 on 2023-03-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_comments_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
