# Generated by Django 4.1.7 on 2023-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_gallery_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="tag",
            field=models.ManyToManyField(related_name="gallery", to="blog.tag"),
        ),
    ]
